lists/config/routes.rb
Rails.application.routes.draw do
  get 'items/create'
  resources :lists do
    resources :items
  end

  root 'lists#index'
end

lists/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lists/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list, required: false
  validates :description, :presence => true

  STATUS = {
    :incomplete => 0,
    :complete => 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

lists/app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  validates :name, :presence => true
end

lists/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lists/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to list_path(@list)
    else 
      render "lists/show"
    end
  end

  private
  def item_params
    params.require(:item).permit(:description)
  end
end

lists/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    #implict rendering lists/index.html.erb
    @list = List.new
    @lists = List.all
    #raise @lists.inspect #check if database query was this succesful
  end

  def show
  #params has all the data passed by a user /lists/:id
    @list = List.find(params[:id])
    @item = Item.new
  end

  def create
    @list = List.new(list_params) #mass assignment
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.all
      render :index
    end
  end

  private
  def list_params #strong params pattern
    params.require(:list).permit(:name)
  end
end

lists/app/helpers/application_helper.rb
module ApplicationHelper
end

lists/app/helpers/items_helper.rb
module ItemsHelper
end

lists/app/helpers/lists_helper.rb
module ListsHelper
end

lists/app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

lists/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

lists/app/views/lists/index.html.erb
<section class="todoapp">

	<header class="header">
		<h1>Your Lists</h1>
		<%= form_for(@list) do |f| %>
				<%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new list name") %>

			<%= f.submit :style => "display: none" %>
		<% end %>
	</header>

  <section class="main">
		<ul class="todo-list">
    <% @lists.each do |list| %>
			<li>
				<div class="view">
					<label><a href="#"><%= link_to list.name, list_path(list) %></a></label>
				</div>
			</li>
		<% end %>
    </ul>

	</section>

	<footer class="footer">

	</footer>
</section>

lists/app/views/lists/show.html.erb
<section class="todoapp">
	<header class="header">
		<h1> <%= @list.name %> </h1>
		<%= form_for([@list, @item]) do |f| %>
		<%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item") %>
		<%= f.submit :style => "display: none" %>
		<% end %>
	</header>

  <section class="main">
		<input class = "toggle-all" type="checkbox">
		<label for="toggle-all">Mark all as complete</label>

		<ul class="todo-list">
			<% @list.items.each do |item| %>
				<li class="<%= "complete" if item.complete? %>">
					<div class="view">
						<%= form_for([@list, item], :url => list_item_path(@list, item)) do |f| %>
							<input class="toggle" type="checkbox" <%= "checked='checked'" if item.complete? %>>
						<% end %>
						<label><%= item.description %></label>
					</div>
				</li>
			<% end %>
    </ul>

	</section>

	<footer class="footer">

	</footer>
</section>